# Generated by Codex on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_studentprofile_disability_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="nis",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.RunSQL(
            sql="UPDATE students_studentprofile SET nis = NULL WHERE nis = '';",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
