# Generated by Django 5.2.13 on 2026-04-23 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_current_enrollments(apps, schema_editor):
    StudentProfile = apps.get_model('students', 'StudentProfile')
    StudyGroup = apps.get_model('academics', 'StudyGroup')
    StudentEnrollment = apps.get_model('students', 'StudentEnrollment')

    students = StudentProfile.objects.exclude(study_group_id__isnull=True).only('id', 'study_group_id')
    for student in students.iterator():
        group = StudyGroup.objects.only('id', 'academic_year_id').get(pk=student.study_group_id)
        StudentEnrollment.objects.get_or_create(
            student_id=student.pk,
            academic_year_id=group.academic_year_id,
            defaults={
                'study_group_id': group.pk,
                'status': 'active',
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0004_alter_studentprofile_nis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('executed', 'Sudah dijalankan')], default='draft', max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_runs', to=settings.AUTH_USER_MODEL)),
                ('source_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_runs_as_source', to='academics.academicyear')),
                ('source_school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_runs', to='academics.schoolclass')),
                ('source_study_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_runs', to='academics.studygroup')),
                ('target_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_runs_as_target', to='academics.academicyear')),
            ],
            options={
                'verbose_name': 'Proses Kenaikan Kelas',
                'verbose_name_plural': 'Proses Kenaikan Kelas',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PromotionRunItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('promote', 'Naik kelas'), ('repeat', 'Tinggal kelas'), ('graduate', 'Lulus'), ('transfer', 'Mutasi'), ('inactive', 'Tidak aktif')], default='promote', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promotion_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='students.promotionrun')),
                ('source_study_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_items_as_source', to='academics.studygroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_items', to='students.studentprofile')),
                ('target_study_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_items_as_target', to='academics.studygroup')),
            ],
            options={
                'verbose_name': 'Detail Kenaikan Kelas',
                'verbose_name_plural': 'Detail Kenaikan Kelas',
                'ordering': ('student__user__full_name',),
                'constraints': [models.UniqueConstraint(fields=('promotion_run', 'student'), name='unique_student_per_promotion_run')],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('repeated', 'Tinggal kelas'), ('graduated', 'Lulus'), ('transferred', 'Mutasi'), ('inactive', 'Tidak aktif')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='academics.academicyear')),
                ('previous_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_enrollments', to='students.studentenrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.studentprofile')),
                ('study_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enrollments', to='academics.studygroup')),
            ],
            options={
                'verbose_name': 'Riwayat Penempatan Siswa',
                'verbose_name_plural': 'Riwayat Penempatan Siswa',
                'ordering': ('academic_year__start_date', 'student__user__full_name'),
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_year'), name='unique_student_enrollment_per_year')],
            },
        ),
        migrations.RunPython(seed_current_enrollments, migrations.RunPython.noop),
    ]
