# Generated by Django 5.2.13 on 2026-04-23 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_promotionrun_promotionrunitem_studentenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAlumniArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('nis', models.CharField(blank=True, max_length=30)),
                ('nisn', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('birth_place', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('mother_name', models.CharField(blank=True, max_length=150)),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('special_needs', models.CharField(blank=True, max_length=150)),
                ('disability_notes', models.CharField(blank=True, max_length=150)),
                ('kip_number', models.CharField(blank=True, max_length=50)),
                ('class_name', models.CharField(blank=True, max_length=100)),
                ('entry_year', models.PositiveIntegerField(blank=True, null=True)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('graduation_status', models.CharField(choices=[('graduated', 'Lulus'), ('transferred', 'Mutasi'), ('other', 'Lainnya')], default='graduated', max_length=20)),
                ('graduation_notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumni_archive', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Data Alumni',
                'verbose_name_plural': 'Data Alumni',
                'ordering': ('-graduation_year', 'full_name'),
            },
        ),
        migrations.CreateModel(
            name='StudentAlumniDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ijazah', 'Ijazah'), ('rapor', 'Rapor'), ('kk', 'Kartu Keluarga'), ('akte', 'Akta Kelahiran'), ('ktp', 'KTP'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='alumni_documents/')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.studentalumniarchive')),
            ],
            options={
                'verbose_name': 'Dokumen Alumni',
                'verbose_name_plural': 'Dokumen Alumni',
                'ordering': ('document_type', '-uploaded_at'),
            },
        ),
    ]
