# Generated by Django 5.2.13 on 2026-04-23 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studentalumniarchive_studentalumnidocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAlumniValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government_name', models.CharField(blank=True, help_text='Nama sesuai sistem pemerintah atau data referensi resmi.', max_length=150)),
                ('diploma_name', models.CharField(blank=True, max_length=150)),
                ('family_card_name', models.CharField(blank=True, max_length=150)),
                ('birth_certificate_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Belum divalidasi'), ('match', 'Cocok'), ('review', 'Perlu revisi'), ('mismatch', 'Tidak cocok')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='students.studentalumniarchive')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumni_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validasi Alumni',
                'verbose_name_plural': 'Validasi Alumni',
                'ordering': ('-validated_at', '-created_at'),
            },
        ),
    ]
