# Generated by Django 5.2.13 on 2026-04-23 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_subject_options_subject_curriculum_and_more'),
        ('students', '0007_studentalumnivalidation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMutationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Mutasi masuk'), ('outbound', 'Mutasi keluar')], max_length=20)),
                ('mutation_date', models.DateField()),
                ('origin_school_name', models.CharField(blank=True, max_length=150)),
                ('origin_school_npsn', models.CharField(blank=True, max_length=20)),
                ('destination_school_name', models.CharField(blank=True, max_length=150)),
                ('destination_school_npsn', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='student_mutations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_mutation_records', to=settings.AUTH_USER_MODEL)),
                ('destination_study_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_mutations_as_destination', to='academics.studygroup')),
                ('origin_study_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_mutations_as_origin', to='academics.studygroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutation_records', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Mutasi Siswa',
                'verbose_name_plural': 'Mutasi Siswa',
                'ordering': ('-mutation_date', '-created_at'),
            },
        ),
    ]
