# Generated by Django 5.2.13 on 2026-04-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentmutationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentalumniarchive',
            name='family_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='family_status',
            field=models.CharField(blank=True, choices=[('lengkap', 'Lengkap'), ('yatim', 'Yatim'), ('piatu', 'Piatu'), ('yatim_piatu', 'Yatim piatu'), ('wali', 'Diasuh wali')], default='', max_length=20),
        ),
    ]
