# Generated by Django 5.2.13 on 2026-04-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_studentalumniarchive_father_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='document_type',
            field=models.CharField(choices=[('kk', 'Kartu Keluarga'), ('akte', 'Akta Kelahiran'), ('ijazah', 'Ijazah'), ('rapor', 'Rapor'), ('kip_pip', 'KIP/PIP'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20),
        ),
    ]
