SUBJECT_PRESETS = [
    {
        "key": "k13-quran-hadis",
        "curriculum": "k13",
        "name": "Al-Qur'an Hadis",
        "code": "QH-K13",
        "category": "agama",
        "description": "Mata pelajaran rumpun PAI pada Kurikulum 2013.",
        "sort_order": 10,
    },
    {
        "key": "k13-akidah-akhlak",
        "curriculum": "k13",
        "name": "Akidah Akhlak",
        "code": "AA-K13",
        "category": "agama",
        "description": "Mata pelajaran rumpun PAI pada Kurikulum 2013.",
        "sort_order": 20,
    },
    {
        "key": "k13-fikih",
        "curriculum": "k13",
        "name": "Fikih",
        "code": "FK-K13",
        "category": "agama",
        "description": "Mata pelajaran rumpun PAI pada Kurikulum 2013.",
        "sort_order": 30,
    },
    {
        "key": "k13-ski",
        "curriculum": "k13",
        "name": "Sejarah Kebudayaan Islam",
        "code": "SKI-K13",
        "category": "agama",
        "description": "Mata pelajaran rumpun PAI pada Kurikulum 2013.",
        "sort_order": 40,
    },
    {
        "key": "k13-bahasa-arab",
        "curriculum": "k13",
        "name": "Bahasa Arab",
        "code": "BAR-K13",
        "category": "agama",
        "description": "Mata pelajaran bahasa Arab pada Kurikulum 2013.",
        "sort_order": 50,
    },
    {
        "key": "k13-ppkn",
        "curriculum": "k13",
        "name": "Pendidikan Pancasila dan Kewarganegaraan",
        "code": "PPKN-K13",
        "category": "umum",
        "description": "Mata pelajaran umum pada Kurikulum 2013.",
        "sort_order": 110,
    },
    {
        "key": "k13-bahasa-indonesia",
        "curriculum": "k13",
        "name": "Bahasa Indonesia",
        "code": "BIN-K13",
        "category": "umum",
        "description": "Mata pelajaran umum pada Kurikulum 2013.",
        "sort_order": 120,
    },
    {
        "key": "k13-matematika",
        "curriculum": "k13",
        "name": "Matematika",
        "code": "MTK-K13",
        "category": "umum",
        "description": "Mata pelajaran umum pada Kurikulum 2013.",
        "sort_order": 130,
    },
    {
        "key": "k13-ipa",
        "curriculum": "k13",
        "name": "Ilmu Pengetahuan Alam",
        "code": "IPA-K13",
        "category": "umum",
        "description": "Mata pelajaran umum pada Kurikulum 2013.",
        "sort_order": 140,
    },
    {
        "key": "k13-ips",
        "curriculum": "k13",
        "name": "Ilmu Pengetahuan Sosial",
        "code": "IPS-K13",
        "category": "umum",
        "description": "Mata pelajaran umum pada Kurikulum 2013.",
        "sort_order": 150,
    },
    {
        "key": "k13-bahasa-inggris",
        "curriculum": "k13",
        "name": "Bahasa Inggris",
        "code": "BIG-K13",
        "category": "umum",
        "description": "Mata pelajaran umum pada Kurikulum 2013.",
        "sort_order": 160,
    },
    {
        "key": "k13-seni-budaya",
        "curriculum": "k13",
        "name": "Seni Budaya",
        "code": "SBD-K13",
        "category": "pengembangan",
        "description": "Mata pelajaran seni dan budaya pada Kurikulum 2013.",
        "sort_order": 170,
    },
    {
        "key": "k13-pjok",
        "curriculum": "k13",
        "name": "Pendidikan Jasmani, Olahraga, dan Kesehatan",
        "code": "PJOK-K13",
        "category": "pengembangan",
        "description": "Mata pelajaran PJOK pada Kurikulum 2013.",
        "sort_order": 180,
    },
    {
        "key": "k13-prakarya",
        "curriculum": "k13",
        "name": "Prakarya",
        "code": "PKY-K13",
        "category": "pengembangan",
        "description": "Mata pelajaran prakarya pada Kurikulum 2013.",
        "sort_order": 190,
    },
    {
        "key": "merdeka-quran-hadis",
        "curriculum": "merdeka",
        "name": "Al-Qur'an Hadis",
        "code": "QH-KM",
        "category": "agama",
        "description": "Mata pelajaran rumpun PAI pada Kurikulum Merdeka.",
        "sort_order": 10,
    },
    {
        "key": "merdeka-akidah-akhlak",
        "curriculum": "merdeka",
        "name": "Akidah Akhlak",
        "code": "AA-KM",
        "category": "agama",
        "description": "Mata pelajaran rumpun PAI pada Kurikulum Merdeka.",
        "sort_order": 20,
    },
    {
        "key": "merdeka-fikih",
        "curriculum": "merdeka",
        "name": "Fikih",
        "code": "FK-KM",
        "category": "agama",
        "description": "Mata pelajaran rumpun PAI pada Kurikulum Merdeka.",
        "sort_order": 30,
    },
    {
        "key": "merdeka-ski",
        "curriculum": "merdeka",
        "name": "Sejarah Kebudayaan Islam",
        "code": "SKI-KM",
        "category": "agama",
        "description": "Mata pelajaran rumpun PAI pada Kurikulum Merdeka.",
        "sort_order": 40,
    },
    {
        "key": "merdeka-bahasa-arab",
        "curriculum": "merdeka",
        "name": "Bahasa Arab",
        "code": "BAR-KM",
        "category": "agama",
        "description": "Mata pelajaran bahasa Arab pada Kurikulum Merdeka.",
        "sort_order": 50,
    },
    {
        "key": "merdeka-pancasila",
        "curriculum": "merdeka",
        "name": "Pendidikan Pancasila",
        "code": "PP-KM",
        "category": "umum",
        "description": "Mata pelajaran umum pada Kurikulum Merdeka.",
        "sort_order": 110,
    },
    {
        "key": "merdeka-bahasa-indonesia",
        "curriculum": "merdeka",
        "name": "Bahasa Indonesia",
        "code": "BIN-KM",
        "category": "umum",
        "description": "Mata pelajaran umum pada Kurikulum Merdeka.",
        "sort_order": 120,
    },
    {
        "key": "merdeka-matematika",
        "curriculum": "merdeka",
        "name": "Matematika",
        "code": "MTK-KM",
        "category": "umum",
        "description": "Mata pelajaran umum pada Kurikulum Merdeka.",
        "sort_order": 130,
    },
    {
        "key": "merdeka-ipa",
        "curriculum": "merdeka",
        "name": "Ilmu Pengetahuan Alam",
        "code": "IPA-KM",
        "category": "umum",
        "description": "Mata pelajaran umum pada Kurikulum Merdeka.",
        "sort_order": 140,
    },
    {
        "key": "merdeka-ips",
        "curriculum": "merdeka",
        "name": "Ilmu Pengetahuan Sosial",
        "code": "IPS-KM",
        "category": "umum",
        "description": "Mata pelajaran umum pada Kurikulum Merdeka.",
        "sort_order": 150,
    },
    {
        "key": "merdeka-ipas",
        "curriculum": "merdeka",
        "name": "Ilmu Pengetahuan Alam dan Sosial",
        "code": "IPAS-KM",
        "category": "umum",
        "description": "Mata pelajaran IPAS pada Kurikulum Merdeka.",
        "sort_order": 155,
    },
    {
        "key": "merdeka-bahasa-inggris",
        "curriculum": "merdeka",
        "name": "Bahasa Inggris",
        "code": "BIG-KM",
        "category": "umum",
        "description": "Mata pelajaran umum pada Kurikulum Merdeka.",
        "sort_order": 160,
    },
    {
        "key": "merdeka-informatika",
        "curriculum": "merdeka",
        "name": "Informatika",
        "code": "INF-KM",
        "category": "umum",
        "description": "Mata pelajaran informatika pada Kurikulum Merdeka.",
        "sort_order": 165,
    },
    {
        "key": "merdeka-seni",
        "curriculum": "merdeka",
        "name": "Seni dan Budaya",
        "code": "SEN-KM",
        "category": "pengembangan",
        "description": "Mata pelajaran seni pada Kurikulum Merdeka.",
        "sort_order": 170,
    },
    {
        "key": "merdeka-pjok",
        "curriculum": "merdeka",
        "name": "Pendidikan Jasmani, Olahraga, dan Kesehatan",
        "code": "PJOK-KM",
        "category": "pengembangan",
        "description": "Mata pelajaran PJOK pada Kurikulum Merdeka.",
        "sort_order": 180,
    },
    {
        "key": "merdeka-p5ppra",
        "curriculum": "merdeka",
        "name": "P5 dan PPRA",
        "code": "P5PPRA-KM",
        "category": "pengembangan",
        "description": "Projek Penguatan Profil Pelajar Pancasila dan Profil Pelajar Rahmatan Lil Alamin.",
        "sort_order": 900,
    },
]


def subject_preset_choices():
    grouped = {}
    for preset in SUBJECT_PRESETS:
        group = "Kurikulum 2013" if preset["curriculum"] == "k13" else "Kurikulum Merdeka"
        grouped.setdefault(group, []).append((preset["key"], f'{preset["name"]} ({preset["code"]})'))
    return [("", "Mapel khusus/manual")] + [(group, choices) for group, choices in grouped.items()]


def get_subject_preset(key):
    return next((preset for preset in SUBJECT_PRESETS if preset["key"] == key), None)
