# Generated by Django 5.2.13 on 2026-04-25 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_alter_subject_options_subject_curriculum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nama sesi ujian')),
                ('semester', models.CharField(choices=[('ganjil', 'Ganjil'), ('genap', 'Genap')], max_length=10, verbose_name='Semester')),
                ('start_date', models.DateField(verbose_name='Tanggal mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal selesai')),
                ('description', models.TextField(blank=True, verbose_name='Keterangan')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_sessions', to='academics.academicyear', verbose_name='Tahun ajaran')),
            ],
            options={
                'verbose_name': 'Sesi Ujian',
                'verbose_name_plural': 'Sesi Ujian',
                'ordering': ('-is_active', '-start_date', '-created_at'),
            },
        ),
    ]
