# Generated by Django 5.2.13 on 2026-04-25 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(verbose_name='Tanggal')),
                ('title', models.CharField(max_length=120, verbose_name='Nama kegiatan')),
                ('item_type', models.CharField(choices=[('exam', 'Mapel ujian'), ('break', 'Istirahat'), ('other', 'Lainnya')], default='exam', max_length=20, verbose_name='Jenis')),
                ('start_time', models.TimeField(verbose_name='Jam mulai')),
                ('end_time', models.TimeField(verbose_name='Jam selesai')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Keterangan')),
                ('sort_order', models.PositiveSmallIntegerField(default=1, verbose_name='Urutan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='exams.examsession', verbose_name='Sesi ujian')),
            ],
            options={
                'verbose_name': 'Jadwal Ujian',
                'verbose_name_plural': 'Jadwal Ujian',
                'ordering': ('exam_date', 'start_time', 'sort_order', 'title'),
            },
        ),
    ]
