# Generated by Codex on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherprofile",
            name="nip",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="nik",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="nuptk",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="task",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="placement",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="total_jtm",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="birth_place",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="madrasah_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.RunSQL(
            sql="UPDATE teachers_teacherprofile SET nip = NULL WHERE nip = '';",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
