# Generated by Django 5.2.13 on 2026-04-23 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_import_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAdditionalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('task_type', models.CharField(choices=[('wali_kelas', 'Wali kelas'), ('pimpinan', 'Pimpinan/koordinator'), ('ekskul', 'Pembina ekstrakurikuler'), ('piket', 'Piket guru'), ('lab_perpus', 'Laboratorium/perpustakaan'), ('administrasi', 'Administrasi madrasah'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('hours_per_week', models.PositiveSmallIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_tasks', to='teachers.teacherprofile')),
            ],
            options={
                'verbose_name': 'Tugas Tambahan Guru',
                'verbose_name_plural': 'Tugas Tambahan Guru',
                'ordering': ('teacher__user__full_name', 'task_type', 'name'),
            },
        ),
    ]
