# Generated by Django 5.2.13 on 2026-04-23 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacheradditionaltask'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherEducationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_level', models.CharField(choices=[('sma', 'SMA/SMK/MA'), ('d3', 'D3'), ('s1', 'S1'), ('s2', 'S2'), ('s3', 'S3'), ('lainnya', 'Lainnya')], default='s1', max_length=20)),
                ('institution_name', models.CharField(max_length=150)),
                ('major', models.CharField(blank=True, max_length=120)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_highest_degree', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_histories', to='teachers.teacherprofile')),
            ],
            options={
                'verbose_name': 'Riwayat Pendidikan Guru',
                'verbose_name_plural': 'Riwayat Pendidikan Guru',
                'ordering': ('teacher__user__full_name', '-graduation_year', 'degree_level'),
            },
        ),
    ]
