# Generated by Django 5.2.13 on 2026-04-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teachereducationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachereducationhistory',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='teacher_diplomas/'),
        ),
        migrations.AddField(
            model_name='teachereducationhistory',
            name='institution_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teachereducationhistory',
            name='institution_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teachereducationhistory',
            name='institution_npsn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='teachereducationhistory',
            name='institution_source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teachereducationhistory',
            name='institution_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
