# Generated by Django 5.2.13 on 2026-04-23 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teachereducationhistory_certificate_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('nip', models.CharField(blank=True, max_length=30)),
                ('nik', models.CharField(blank=True, max_length=30)),
                ('nuptk', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('task', models.CharField(blank=True, max_length=150)),
                ('placement', models.CharField(blank=True, max_length=150)),
                ('total_jtm', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('birth_place', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('madrasah_email', models.EmailField(blank=True, max_length=254)),
                ('employment_status', models.CharField(choices=[('tetap', 'Tetap'), ('honorer', 'Honorer'), ('kontrak', 'Kontrak')], max_length=20)),
                ('exit_status', models.CharField(choices=[('pensioned', 'Pensiun'), ('transferred', 'Pindah'), ('other', 'Lainnya')], default='other', max_length=20)),
                ('exit_notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive', to='teachers.teacherprofile')),
            ],
            options={
                'verbose_name': 'Arsip Guru',
                'verbose_name_plural': 'Arsip Guru',
                'ordering': ('-archived_at', 'full_name'),
            },
        ),
        migrations.CreateModel(
            name='TeacherMutationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Mutasi masuk'), ('outbound', 'Mutasi keluar')], max_length=20)),
                ('mutation_date', models.DateField()),
                ('origin_school_name', models.CharField(blank=True, max_length=150)),
                ('destination_school_name', models.CharField(blank=True, max_length=150)),
                ('origin_placement', models.CharField(blank=True, max_length=150)),
                ('destination_placement', models.CharField(blank=True, max_length=150)),
                ('exit_status', models.CharField(blank=True, choices=[('pensioned', 'Pensiun'), ('transferred', 'Pindah'), ('other', 'Lainnya')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='teacher_mutations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_mutation_records', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutation_records', to='teachers.teacherprofile')),
            ],
            options={
                'verbose_name': 'Mutasi Guru',
                'verbose_name_plural': 'Mutasi Guru',
                'ordering': ('-mutation_date', '-created_at'),
            },
        ),
    ]
