# Generated by Django 5.2.13 on 2026-04-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=150, verbose_name='Nama madrasah')),
                ('npsn', models.CharField(max_length=20, verbose_name='NPSN')),
                ('nsm', models.CharField(blank=True, max_length=30, verbose_name='NSM')),
                ('legal_name', models.CharField(blank=True, max_length=150, verbose_name='Nama legal')),
                ('address', models.CharField(max_length=255, verbose_name='Alamat')),
                ('village', models.CharField(blank=True, max_length=100, verbose_name='Desa / Kelurahan')),
                ('district', models.CharField(max_length=100, verbose_name='Kecamatan')),
                ('regency', models.CharField(max_length=100, verbose_name='Kabupaten / Kota')),
                ('province', models.CharField(max_length=100, verbose_name='Provinsi')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Kode pos')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Telepon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Situs web')),
                ('principal_name', models.CharField(max_length=150, verbose_name='Nama kepala madrasah')),
                ('principal_nip', models.CharField(max_length=30, verbose_name='NIP kepala madrasah')),
                ('operator_name', models.CharField(blank=True, max_length=150, verbose_name='Nama operator')),
                ('operator_phone', models.CharField(blank=True, max_length=20, verbose_name='Nomor operator')),
                ('letter_footer', models.CharField(blank=True, max_length=255, verbose_name='Catatan footer surat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Identitas Madrasah',
                'verbose_name_plural': 'Identitas Madrasah',
            },
        ),
    ]
