# Generated by Django 5.2.13 on 2026-04-22 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contoh: 2026/2027', max_length=30, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tahun Ajaran',
                'verbose_name_plural': 'Tahun Ajaran',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contoh: Kelas 7, Kelas 8, XI Keagamaan', max_length=100, unique=True)),
                ('level_order', models.PositiveSmallIntegerField(default=1, help_text='Urutan kelas untuk tampilan')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kelas',
                'verbose_name_plural': 'Kelas',
                'ordering': ('level_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contoh: 7A, 8B, XI Keagamaan 1', max_length=100)),
                ('capacity', models.PositiveIntegerField(default=32)),
                ('room_name', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_groups', to='academics.academicyear')),
                ('homeroom_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_groups', to='teachers.teacherprofile')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_groups', to='academics.schoolclass')),
            ],
            options={
                'verbose_name': 'Rombel',
                'verbose_name_plural': 'Rombel',
                'ordering': ('school_class__level_order', 'name'),
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'name'), name='unique_study_group_per_year')],
            },
        ),
    ]
