# Generated by Django 5.2.13 on 2026-04-23 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0005_promotionrun_promotionrunitem_studentenrollment'),
        ('teachers', '0002_teacher_import_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('category', models.CharField(choices=[('agama', 'Keagamaan'), ('umum', 'Umum'), ('lokal', 'Muatan lokal'), ('pengembangan', 'Pengembangan diri')], default='umum', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mata Pelajaran',
                'verbose_name_plural': 'Mata Pelajaran',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_score', models.PositiveSmallIntegerField(default=75)),
                ('weekly_hours', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.schoolclass')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_subjects', to='teachers.teacherprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Mapel Per Kelas',
                'verbose_name_plural': 'Mapel Per Kelas',
                'ordering': ('school_class__level_order', 'subject__sort_order', 'subject__name'),
            },
        ),
        migrations.CreateModel(
            name='GradeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('ganjil', 'Ganjil'), ('genap', 'Genap')], default='ganjil', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('locked', 'Dikunci')], default='draft', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_books', to='academics.academicyear')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_books', to='academics.classsubject')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_books', to=settings.AUTH_USER_MODEL)),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_books', to='academics.studygroup')),
            ],
            options={
                'verbose_name': 'Ledger Nilai',
                'verbose_name_plural': 'Ledger Nilai',
                'ordering': ('-academic_year__start_date', 'semester', 'study_group__school_class__level_order', 'study_group__name', 'class_subject__subject__sort_order'),
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('skill_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attitude', models.CharField(blank=True, choices=[('A', 'Sangat baik'), ('B', 'Baik'), ('C', 'Cukup'), ('D', 'Perlu pembinaan')], max_length=1)),
                ('teacher_notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='academics.gradebook')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Nilai Siswa',
                'verbose_name_plural': 'Nilai Siswa',
                'ordering': ('student__user__full_name',),
            },
        ),
        migrations.AddConstraint(
            model_name='gradebook',
            constraint=models.UniqueConstraint(fields=('study_group', 'class_subject', 'semester'), name='unique_grade_book_per_group_subject_semester'),
        ),
        migrations.AddConstraint(
            model_name='studentgrade',
            constraint=models.UniqueConstraint(fields=('grade_book', 'student'), name='unique_student_grade_per_grade_book'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.UniqueConstraint(fields=('school_class', 'subject'), name='unique_subject_per_school_class'),
        ),
    ]
