# Generated by Django 5.2.13 on 2026-04-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject_classsubject_gradebook_studentgrade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('curriculum', 'sort_order', 'name'), 'verbose_name': 'Mata Pelajaran', 'verbose_name_plural': 'Mata Pelajaran'},
        ),
        migrations.AddField(
            model_name='subject',
            name='curriculum',
            field=models.CharField(choices=[('lintas', 'Lintas kurikulum'), ('k13', 'Kurikulum 2013'), ('merdeka', 'Kurikulum Merdeka')], default='lintas', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('curriculum', 'name'), name='unique_subject_name_per_curriculum'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False)), fields=('curriculum', 'code'), name='unique_subject_code_per_curriculum'),
        ),
    ]
