# Generated by Django 5.2.13 on 2026-04-26 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_subject_options_subject_curriculum_and_more'),
        ('teachers', '0006_teacherarchive_teachermutationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PbmScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('1', 'Senin'), ('2', 'Selasa'), ('3', 'Rabu'), ('4', 'Kamis'), ('5', 'Jumat'), ('6', 'Sabtu')], max_length=1)),
                ('lesson_order', models.PositiveSmallIntegerField(verbose_name='Jam ke-')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('room_name', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pbm_schedule_slots', to='academics.academicyear')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pbm_schedule_slots', to='academics.classsubject')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pbm_schedule_slots', to='academics.schoolclass')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbm_schedule_slots', to='teachers.teacherprofile')),
            ],
            options={
                'verbose_name': 'Slot Jadwal PBM',
                'verbose_name_plural': 'Slot Jadwal PBM',
                'ordering': ('school_class__level_order', 'day_of_week', 'lesson_order'),
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'school_class', 'day_of_week', 'lesson_order'), name='unique_pbm_slot_per_class_day_order')],
            },
        ),
    ]
