# Generated by Django 5.2.13 on 2026-04-26 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_pbmscheduleslot'),
        ('teachers', '0006_teacherarchive_teachermutationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='RombelTeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_score', models.PositiveSmallIntegerField(default=75)),
                ('weekly_hours', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rombel_assignments', to='academics.studygroup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rombel_assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rombel_assignments', to='teachers.teacherprofile')),
            ],
            options={
                'verbose_name': 'Mapel Diajar per Rombel',
                'verbose_name_plural': 'Mapel Diajar per Rombel',
                'ordering': ('study_group__academic_year__start_date', 'study_group__school_class__level_order', 'study_group__name', 'subject__sort_order', 'subject__name'),
                'constraints': [models.UniqueConstraint(fields=('study_group', 'subject'), name='unique_subject_per_study_group')],
            },
        ),
    ]
